<R>             ::= <O><I>
<O>             ::= "SEP_t("<binario>")"
<I>             ::= <AP3_t_1><UFO_t_1><FUL_t_1><FT_t_1><AP1_t_1><EMF1_t_1><LFY_t_1><AP2_t_1><WUS_t_1><AG_t_1><LUG_t_1><CLF_t_1><TFL1_t_1><PI_t_1><SEP_t_1>
<AP3_t_1>      ::= "AP3_t_1("<binario>")" | ""
<UFO_t_1>      ::= "UFO_t_1("<binario>")" | ""
<FUL_t_1>      ::= "FUL_t_1("<binario>")" | ""
<FT_t_1>       ::= "FT_t_1("<binario>")" | ""
<AP1_t_1>      ::= "AP1_t_1("<binario>")" | ""
<EMF1_t_1>     ::= "EMF1_t_1("<binario>")" | ""
<LFY_t_1>      ::= "LFY_t_1("<binario>")" | ""
<AP2_t_1>      ::= "AP2_t_1("<binario>")" | ""
<WUS_t_1>      ::= "WUS_t_1("<binario>")" | ""
<AG_t_1>      ::= "AG_t_1("<binario>")" | ""
<LUG_t_1>      ::= "LUG_t_1("<binario>")" | ""
<CLF_t_1>      ::= "CLF_t_1("<binario>")" | ""
<TFL1_t_1>     ::= "TFL1_t_1("<binario>")" | ""
<PI_t_1>       ::= "PI_t_1("<binario>")" | ""
<SEP_t_1>      ::= "SEP_t_1("<binario>")" | ""
<binario>       ::= 0 | 1 