<R>             ::= <O><I>
<O>             ::= "y1("<binario>")"
<I>             ::= <x0><x1><x2>
<x0>            ::= "x0("<binario>")" | ""
<x1>            ::= "x1("<binario>")" | ""
<x2>            ::= "x2("<binario>")" | ""
<binario>       ::= 0 | 1 